type Apartment {
  id: ID!
  totalArea: Float!
  identifier: Int!
  privateArea: Float!
  building: Building @relation(name: "BUILDING_APARTMENTS", direction: "IN")
}

type Building {
  id: ID!
  name: String!
  apartments: [Apartment!]! @relation(name: "BUILDING_APARTMENTS", direction: "OUT")
}

type Condominium {
  id: ID!
  cnpj: String!
}

type Street {
  id: ID!
  name: String!
}